### ISSUE TITLE
Mobs aren't spawning. This might help determine why.

### ISSUE THREAD

**Issue by ac7web** [Civcraft/MusterCull#15]
https://bugs.mojang.com/browse/MC-42053

As I mentioned to ttk, I ran a test on a vanilla MC server in 1.8 with a low chunk loading distance and my mob grinder suddenly just stopped producing mobs. I increased the chunk loading distance again and it magically fixed it.

This issue is new to 1.7 I think.

I'm not necessarily suggesting we permanently change the mob cap but if a five minute test helps us determine where, in the code, the lack of spawns in coming from, might it be worth testing this? This could at least be part of the problem.

**Comment by ttk2** [comment]
whats the suggestion bump the view distance to 10?

**Comment by ac7web** [comment]
Yes, if only to run a simple test to confirm this causes the issue. If it does, that's something to go on at least.

**Comment by ttk2** [comment]
that's some what difficult to do if we only restart once that day, I will
have to make a point to restart the server, what view distance to the
problems supposedly start at?

**Comment by ac7web** [comment]
I think the problem occurred when I had a view distance lower than 10. I have it set to 10 now on my server and everything works fine.

**Comment by ttk2** [comment]
that's not a solution a view distance of 10 is a lot more than 10 times the
server load, that's hundreds of chunks per player, view distance 4 is 64
chunks per player.

**Comment by ac7web** [comment]
I didn't mean you should leave it at that but if it show that this improves spawning then it would indicate where the problem might be occurring in the code. If you don't want to run this test on CivCraft, I totally understand but perhaps you (or someone else) could replicate the same experiment on CivTest, with a limited number of players?

**Comment by ttk2** [comment]
I think civtest has a higher view distance already.

**Comment by TealNerd** [comment]
view dist of 4 is 81 chunks actually

**Comment by jjj5311** [comment]
this can be closed now?

**Comment by ttk2** [comment]
yes
