### ISSUE TITLE
mob radius should use X/Z with full Y range

### ISSUE THREAD

**Issue by WildWeazel** [Civcraft/MusterCull#20]

**Comment by WildWeazel** [comment]
29539877dac793d66be987e9ea468c451b52f1f4

**Comment by WildWeazel** [comment]
http://civcraft.co:8080/job/MusterCull-master/38/

**Comment by ttk2** [comment]
sweet thanks. Did anyone review the pull?

**Comment by ProgrammerDan** [comment]
It looked good to me, straightforward change.

**Comment by ttk2** [comment]
sweet to Civtest this goes

**Comment by ProgrammerDan** [comment]
I'm guessing expected behavior a.la civtest would be that vertical farms will die off to within mustercull's config.yml parameters?

**Comment by WildWeazel** [comment]
yep, anything within _range_ blocks horizontally, bedrock to sky limit

**Comment by ttk2** [comment]
any testing occur on this?

**Comment by dbear20** [comment]
I believe this is on the live server now so can one of the admins close it.
