### ISSUE TITLE
1.8.3 compatibility

### ISSUE THREAD

**Issue by dbear20** [Civcraft/MusterCull#22]
Spigot started filtering out large ranges in 1.8.3 as can be seen [here](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/21f6ee1f627245705a9741d1665dffef833ad232). This cause mustercull to have issues with our current ranges we have set in the config (160), the console is spammed with the spigot warning message which can be seen [here](http://imgur.com/eys3aJm). I played around with the config ranges and found it basically disables mustercull once you get into the mid 80's for the range as its always filtering out the call. Below that though and it only filters out the call every now and then if you are close to the mid 80's but i have yet to have it filter below 80.

Other than this range limitation it automatically pulls in all the new mobs and works perfectly on them as can be seen in these [photos](http://imgur.com/a/dpHTK).

**Comment by rourke750** [comment]
Unfortunately I dont think there is anything we can do about this :(

**Comment by ttk2** [comment]
just hard code the range for culling to the 80 somthing value, hopefully the new entity tick portion adjustment ability in 1.8 will help.

**Comment by dbear20** [comment]
Could also just not allow any values above 80 like was done on another setting since we probably aren't the only ones to use it.

I may be able to do something like that since it should be just copying and pasting the code around but I wouldn't be able to compile and test it locally. Should I try and make the changes or should I just let it for someone else?

**Comment by rourke750** [comment]
Go for it and send a pull.

**Comment by rourke750** [comment]
https://github.com/Civcraft/MusterCull/commit/cb381f734f20eefa28debc13770ad0b61c4a7878
