### ISSUE TITLE
No license 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/MusterCull#32]
This plugin needs to be licensed.

**Comment by drjawa** [comment]
L0stman is creator right? We'll need to contact him somehow.

**Comment by ttk2** [comment]
Celdecia is, got his agreement, emailed everyone else.

**Comment by ttk2** [comment]
so far we have approval from

Roruke
Celdecea
Wild
felzix
Gavin
dbear
erocs

missing

Lostman
IslandProdigy
Pruby

at least I think so, I don't remember peoples real names and email are
mostly that.
