### ISSUE TITLE
Track multiple entities and cancel spawn

### ISSUE THREAD

**Issue by rourke750** [Civcraft/MusterCull#33]
After x amount of multiple spawn in an area spawn one mob with the combined drops of all mobs that should have spawned in an area.

**Comment by rourke750** [comment]
@ProgrammerDan @Xavter @BlackXnt  Anyone of you want to tackle this?

**Comment by BlackXnt** [comment]
I will take everything related to MusterCull.

**Comment by rourke750** [comment]
Oh also make it configurable.  Do you get what im trying to say or do you need me to explain it more.

**Comment by BlackXnt** [comment]
I got it. Shouldn't be hard to code too.

**Comment by ttk2** [comment]
this should be a nice to have after the general overhaul although this will
have a big impact

**Comment by rourke750** [comment]
@ttk2 Would make it better as we wouldn't have to kill mobs.

@BlackXnt Could you also make it so it scans the surrounding area and merges similar mobs as well.

**Comment by ttk2** [comment]
hmm, so you want to totally avoid killing them and just stack them all the
time?

**Comment by BlackXnt** [comment]
@ttk2 Why not making it one the main features? We can have the same drop rate as vanilla with minimum amounts of mobs.

@rourke750 Can you explain more?

**Comment by ttk2** [comment]
I can agree with that, go for it if you think its the best solution, you
have flexibility in how you get to the goal .

**Comment by rourke750** [comment]
@ttk2 Configurable at least but yes.  We wouldnt need to use the mob drops multiplier in humbug if we had normal spawning.  Not to mention this would solve the amount of entities in pins as huge amount would be merged into one mob,

@BlackXnt So lets say you have multiple pens which have cows in them.  Maybe 4 cows in each pen.  Well they were all breeded naturally unlike the issue with pigmen where we flat out just want to build a pigmans drops before spawning it.  So you spawn an egg and there are multiple cows in a field and they are already existent and close enough that they get merged together and have combined drops.

**Comment by BlackXnt** [comment]
@rourke750 I see. But in this case we dont want to combine all the cows into one cow. Otherwise players won't be able to breed animals at all. We should make sure to always keep at least 2 animals.

**Comment by rourke750** [comment]
Good point.

**Comment by rourke750** [comment]
@BlackXnt Most of these ideas are from a plugin hcf has apparently.  I think for they just have it that if an animal is merged and you try breed it works anyways.

**Comment by ProgrammerDan** [comment]
Also make sure that the drops aren't strictly death drops. Sheep specifically comes to mind, also mooshrooms; make sure they drop an appropriately increased amount of wool and mushrooms, respectively, when hit with sheers after being combined.

**Comment by rourke750** [comment]
@BlackXnt How goes it?  Any progress?

**Comment by ttk2** [comment]
he said he would get started this weekend.

**Comment by rourke750** [comment]
Ah k

**Comment by BlackXnt** [comment]
Ok I am almost done, I only need to do the scheduler now. Hopefully we will have a version for testing by the end of the week.

**Comment by ttk2** [comment]
sounds great! Thanks.

**Comment by BlackXnt** [comment]
I have done more progress today, mostly testing on my local server and fixing bugs. If anything goes smoothly you should expect a pull by tomorrow night - saturday morning.

**Comment by BlackXnt** [comment]
https://github.com/Civcraft/MusterCull/blob/master/MusterCull/config.yml#L201

@ttk2 Why is this set to 15? Default is 1.

**Comment by ttk2** [comment]
That's something that supposed to keep all of a rare mob from being culled.

**Comment by BlackXnt** [comment]
15 percent is way too high. From looking in the code a mob must be 15 percent from all kind of entities in all worlds(not even just mobs) to even be considered to be culled.

**Comment by ttk2** [comment]
then change it to whatever you think will work, we do need a better way to ensure that small pop mobs don't get culled to aggressively.

**Comment by BlackXnt** [comment]
https://github.com/Civcraft/MusterCull/pull/37
