### ISSUE TITLE
Endermen spawning is embarrassingly low

### ISSUE THREAD

**Issue by Grayyer** [Civcraft/MusterCull#40]
After speaking with a few people who man the end farms, it appears that a given platform only yields 3 to 5 endermen spawns per hour. 

Depending on which players are logged in, I am able to get a few sets of 2-3 endermen spawn onto my platform, yielding me up to 4 stacks of pearls (per hour)... Or I could wait for over 3 hours before a single enderman spawns.

This should not be this low, should it?

**Comment by ttk2** [comment]
what sort of drops do they have? Mustercull is doing spawn combining now (more than one mob becomes a single one but has increased drops) maybe the extra drops are not working.

**Comment by Grayyer** [comment]
Like I said, if I am one of the few people logged in, I am able to get up to 4 stacks of pearls per hour.

I think the largest amount of pearls I got (with loot3) from a single endermen is 8.

**Comment by ttk2** [comment]
@BlackXnt thoughts?

**Comment by BlackXnt** [comment]
I completely missed this issue.

Are you using the 1.8 design? I am seeing a lot of endermen in the overworld after the recent changes. Mustercull doesn't cull endermen at all, so I am not sure what can be the issue.

**Comment by ProgrammerDan** [comment]
From recent server timings looks like enderman spawning is back to healthy levels, closing this for now. Reopen if I'm wrong.
