### ISSUE TITLE
MusterCull needs to block mob drops from the mobs it kills

### ISSUE THREAD

**Issue by ttk2** [Civcraft/MusterCull#8]
* [MusterCull needs to block mob drops from the mobs it kills](https://pay.reddit.com/r/Civcraft/comments/2s3369/why_arent_my_pigmen_spontaneously_dying/), for the sake of my sanity. It seems like we might only be a few poorly designed grinders away from decent performance.

**Comment by rourke750** [comment]
From my update to mustercull it doesnt seem like dropped entities are even close to the amount of lag that we are suffering on the server.  Also most time when multiple mobs die, lets say three in a surronded area, most often their items join together in an itemstack to make it count as 1 entity as opposed to the previous three as well as the server no longer performs the ai computations on the dead entity.

**Comment by ttk2** [comment]
so then what is the major issue?

**Comment by rourke750** [comment]
@erocs Any idea on the approach to finding out where exactly the most influential area is?

**Comment by rourke750** [comment]
Is this till wanted?

**Comment by erocs** [comment]
How will it identify them to prevent the item drops? It just uses damage
over time to slowly kill them.

**Comment by rourke750** [comment]
I believe entities have an id, we could track through that.

**Comment by ttk2** [comment]
not sure, what does everyone think?

**Comment by BlackXnt** [comment]
Is this still needed?

**Comment by erocs** [comment]
I thought it now merged all of the culled mob drops into an existing mob.
It would seem that this is obsolete.

**Comment by BlackXnt** [comment]
You can close this.
